# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [ ]:
#exercise 1.1

In [1]:
!pip install Numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 4.5 MB/s eta 0:00:00a 0:00:01


In [ ]:
#exercise 1.2

In [4]:
import numpy as np

In [ ]:
#exercise 1.3

In [5]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [ ]:
#exercise 1.4

In [7]:
print(data[0])

1


In [8]:
print(data[1:4])

[2 3 4]


In [9]:
print(np.sort(data))

[1 2 3 4 5]


In [10]:
#exercise 1.5

In [12]:
arr = np.array([3, 2, 14, 9, 10, 12])

In [17]:
print(arr[3])

9


In [18]:
#exercise 1.6

In [20]:
arr1 = np.array([[9, 5, 8],[55, 89, 76]])


In [21]:
print(arr1)

[[ 9  5  8]
 [55 89 76]]
